# Generated by Django 4.2.1 on 2024-02-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=256)),
                ('isi', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateField(auto_now=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
